import type { PuzzleWord } from "./types";

// Curated NIV vocabulary. Only individual words and references are stored; no
// copyrighted verse text is reproduced. Proper names are intentionally allowed.
export const SOLUTION_WORDS: PuzzleWord[] = [
  { word: "aaron", reference: "Exodus 4:14" },
  { word: "abram", reference: "Genesis 12:1" },
  { word: "alive", reference: "Romans 6:11" },
  { word: "altar", reference: "Genesis 8:20" },
  { word: "angel", reference: "Luke 1:26" },
  { word: "armor", reference: "Ephesians 6:11" },
  { word: "asher", reference: "Genesis 30:13" },
  { word: "babel", reference: "Genesis 11:9" },
  { word: "bless", reference: "Psalm 103:1" },
  { word: "bread", reference: "John 6:35" },
  { word: "bride", reference: "Revelation 21:2" },
  { word: "caleb", reference: "Numbers 14:24" },
  { word: "cedar", reference: "Psalm 92:12" },
  { word: "child", reference: "Matthew 18:2" },
  { word: "cloak", reference: "2 Timothy 4:13" },
  { word: "coins", reference: "Luke 15:8" },
  { word: "cross", reference: "Luke 9:23" },
  { word: "crown", reference: "James 1:12" },
  { word: "david", reference: "1 Samuel 16:13" },
  { word: "death", reference: "Romans 6:23" },
  { word: "dream", reference: "Genesis 37:5" },
  { word: "eagle", reference: "Isaiah 40:31" },
  { word: "earth", reference: "Genesis 1:1" },
  { word: "egypt", reference: "Exodus 12:31" },
  { word: "elder", reference: "1 Timothy 5:1" },
  { word: "faith", reference: "Hebrews 11:1" },
  { word: "field", reference: "Matthew 13:44" },
  { word: "first", reference: "Matthew 20:16" },
  { word: "flood", reference: "Genesis 7:17" },
  { word: "forty", reference: "Matthew 4:2" },
  { word: "fruit", reference: "Galatians 5:22" },
  { word: "gates", reference: "Psalm 100:4" },
  { word: "giant", reference: "1 Samuel 17:4" },
  { word: "glory", reference: "John 1:14" },
  { word: "goats", reference: "Matthew 25:32" },
  { word: "grace", reference: "Ephesians 2:8" },
  { word: "grape", reference: "Micah 7:1" },
  { word: "groom", reference: "Matthew 25:6" },
  { word: "hagar", reference: "Genesis 16:8" },
  { word: "heart", reference: "Proverbs 4:23" },
  { word: "heard", reference: "1 John 1:1" },
  { word: "hills", reference: "Psalm 121:1" },
  { word: "honey", reference: "Psalm 119:103" },
  { word: "horse", reference: "Revelation 19:11" },
  { word: "house", reference: "Joshua 24:15" },
  { word: "isaac", reference: "Genesis 21:3" },
  { word: "jacob", reference: "Genesis 32:28" },
  { word: "james", reference: "Matthew 4:21" },
  { word: "jesse", reference: "1 Samuel 16:1" },
  { word: "jesus", reference: "Matthew 1:21" },
  { word: "jonah", reference: "Jonah 1:1" },
  { word: "judge", reference: "Judges 2:18" },
  { word: "judah", reference: "Genesis 29:35" },
  { word: "lambs", reference: "John 21:15" },
  { word: "learn", reference: "Matthew 11:29" },
  { word: "light", reference: "John 8:12" },
  { word: "lions", reference: "Daniel 6:22" },
  { word: "lydia", reference: "Acts 16:14" },
  { word: "manna", reference: "Exodus 16:31" },
  { word: "mercy", reference: "Luke 6:36" },
  { word: "micah", reference: "Micah 1:1" },
  { word: "moses", reference: "Exodus 3:4" },
  { word: "mount", reference: "Exodus 19:20" },
  { word: "naomi", reference: "Ruth 1:2" },
  { word: "night", reference: "Genesis 1:5" },
  { word: "olive", reference: "Genesis 8:11" },
  { word: "paths", reference: "Proverbs 3:6" },
  { word: "peace", reference: "John 14:27" },
  { word: "peter", reference: "Matthew 16:18" },
  { word: "psalm", reference: "Psalm 98:1" },
  { word: "queen", reference: "Esther 2:17" },
  { word: "rahab", reference: "Joshua 2:1" },
  { word: "raven", reference: "Genesis 8:7" },
  { word: "river", reference: "Genesis 2:10" },
  { word: "robes", reference: "Revelation 7:9" },
  { word: "rooms", reference: "John 14:2" },
  { word: "royal", reference: "1 Peter 2:9" },
  { word: "sarah", reference: "Genesis 17:15" },
  { word: "saved", reference: "Ephesians 2:8" },
  { word: "serve", reference: "Joshua 24:15" },
  { word: "seven", reference: "Genesis 2:2" },
  { word: "sheep", reference: "John 10:11" },
  { word: "sinai", reference: "Exodus 19:11" },
  { word: "sling", reference: "1 Samuel 17:40" },
  { word: "snake", reference: "Numbers 21:9" },
  { word: "sodom", reference: "Genesis 19:24" },
  { word: "songs", reference: "Ephesians 5:19" },
  { word: "speak", reference: "1 Samuel 3:10" },
  { word: "spear", reference: "1 Samuel 17:7" },
  { word: "stars", reference: "Genesis 15:5" },
  { word: "stone", reference: "Matthew 28:2" },
  { word: "sword", reference: "Ephesians 6:17" },
  { word: "teach", reference: "Matthew 28:20" },
  { word: "third", reference: "1 Corinthians 15:4" },
  { word: "titus", reference: "Titus 1:4" },
  { word: "tower", reference: "Genesis 11:4" },
  { word: "trust", reference: "Proverbs 3:5" },
  { word: "truth", reference: "John 14:6" },
  { word: "walls", reference: "Joshua 6:20" },
  { word: "water", reference: "John 4:14" },
  { word: "wheat", reference: "Matthew 13:25" },
  { word: "widow", reference: "Mark 12:42" },
  { word: "woman", reference: "John 4:7" },
  { word: "world", reference: "John 3:16" },
  { word: "wrote", reference: "John 19:22" },
  { word: "yeast", reference: "Matthew 13:33" },
  { word: "youth", reference: "1 Timothy 4:12" }
];

const COMMON_GUESSES = `about above abuse actor acute admit adopt adult after again agent agree ahead alarm album alert alike alive allow alone along alter among anger angle angry apart apple apply arena argue arise array aside asset audio audit avoid award aware badly baker bases basic beach began begin begun being below bench bible birth black blame blind block blood board boast bound brain brand bread break breed brief bring broad broke brown build built buyer cable carry catch cause chain chair chart chase cheap check chest chief child chose civil claim class clean clear clerk click climb clock close cloud coach coast could count court cover craft crash cream crime cross crowd crown curve cycle daily dance dealt death debut delay depth diary dirty doubt dozen draft drama drawn dream dress drill drink drive drove dying eager early earth eight elite empty enemy enjoy enter entry equal error event every exact exist extra faith false fault favor feast fiber field fifth fifty fight final first fixed flame flash fleet floor fluid focus force forth forty forum found frame fresh front fruit fully funny giant given glass globe glory going grace grade grand grant grass great green gross group grown guard guess guest guide habit happy heart heavy hence horse hotel house human ideal image index inner input issue judge known label large later laugh layer learn least leave light limit local logic loose lower lucky lunch lying magic major maker march match maybe mayor meant media mercy metal might minor model money month moral motor mount mouse mouth movie music needs never newly night noise north novel nurse occur ocean offer often order other ought outer owner paint panel paper party peace phase phone photo piece pilot pitch place plain plane plant plate point pound power press price pride prime print prior prize proof proud prove queen quick quiet quite radio raise range rapid ratio reach ready refer right rival river rough round route royal rural scale scene scope score sense serve seven shall shape share sharp sheet shelf shell shift shine shirt shock shoot short shown sight since skill sleep slice slide small smart smile solid solve sorry sound south space spare speak speed spend spent split spoke sport staff stage stand start state steam steel stick still stock stone stood store storm story strip stuck study stuff style sugar table taken taste teach teeth thank their theme there thick thing think third those three throw tight tired title today topic total touch tough tower track trade train treat trend trial tribe trick tried truck truly trust truth twice under union unity until upper upset urban usage usual valid value video visit vital voice waste watch water wheel where which while white whole whose woman women world worry worse worst worth would wound write wrong wrote young youth`.split(/\s+/);

export const ALLOWED_GUESSES = new Set([
  ...COMMON_GUESSES,
  ...SOLUTION_WORDS.map(({ word }) => word),
]);
